"use client";

import type { CameraConfig, SurfaceOverride } from "@/components/room-scene";
import { RoomScene } from "@/components/room-scene";
import type { Product } from "@/components/product-card";

/**
 * `modern_bathroom.glb` (sourced from Sketchfab, not generated by
 * `scripts/generate-room-models.mjs`). Its own camera rig and tileable-mesh
 * list live here rather than in `room-scene.tsx`'s internal maps — see
 * `components/visualizer/living-room.tsx` for the reasoning.
 */
const MODEL_URL = "/models/rooms/modern_bathroom.glb";

/**
 * Floor and walls are separate meshes (no `combinedShell`), but
 * `Bathroom_SideWalls_0` still welds the ceiling into the wall geometry —
 * `peelCeilingFromWalls` tells `RoomScene` to keep those near-horizontal
 * faces on the plaster via `prepareWallGroups`. Both meshes also ship with
 * 0..1 UVs; metre UV rewrite happens in `RoomScene` the same way as the
 * living room.
 */
const SURFACE_OVERRIDE: SurfaceOverride = {
  floor: ["Bathroom_Floor_0"],
  wall: ["Bathroom_BackWall_0", "Bathroom_SideWalls_0"],
  peelCeilingFromWalls: true,
};

/**
 * Measured the same way as the other sourced models: dumped
 * `Box3.setFromObject` per mesh from inside the browser. This one is a
 * narrow room — x -1.44..1.64 (3.08 m wide), z -2.30..1.90 (4.2 m deep),
 * floor at y≈0.12, ceiling at y≈2.45 — with every fixture (mirror, pendant
 * light, sink cabinet, toilet, framed art) mounted on the back wall at
 * z≈1.8-1.9, and the window on the right side wall (x≈1.55) roughly midway
 * down the room. The front third (z below ~0) is empty floor. `target`/
 * `position` face the back wall head-on from that empty front area — the
 * same straight, centred composition the customer's own reference shot
 * uses, rather than an angled corner view.
 */
const CAMERA_CONFIG: CameraConfig = {
  position: [0.1, 1.35, -2.1],
  target: [0.1, 1.2, 1.8],
  near: 0.1,
  far: 60,
  horizontalFov: 78,
  orbitLimits: {
    minDistance: 2.2,
    // Zoomed all the way out, this is the customer's own reference shot:
    // the whole back wall (mirror, light, cabinet, toilet, art) framed
    // head-on, with margin of floor and ceiling around it — see the
    // model's own screenshot this was matched against.
    maxDistance: 4.1,
    minAzimuthAngle: (160 * Math.PI) / 180,
    maxAzimuthAngle: (200 * Math.PI) / 180,
    minPolarAngle: (80 * Math.PI) / 180,
    maxPolarAngle: (100 * Math.PI) / 180,
  },
  /**
   * Keeps the camera inside the room regardless of what the orbit limits
   * alone allow — the same guarantee as the other rooms' `bounds`, see
   * `ContainCamera` in `room-scene.tsx`. `max.z` stops short of the sink
   * cabinet/toilet against the back wall; `min.z` stops short of the front
   * wall (floor runs to z≈-2.3).
   */
  bounds: {
    min: [-1.1, 0.3, -2.15],
    max: [1.3, 2.2, 1.3],
  },
};

export const Bathroom = ({
  floorTile,
  wallTile,
  className,
}: {
  floorTile?: Product;
  wallTile?: Product;
  className?: string;
}) => (
  <RoomScene
    modelUrl={MODEL_URL}
    floorTile={floorTile}
    wallTile={wallTile}
    className={className}
    cameraConfig={CAMERA_CONFIG}
    surfaceOverride={SURFACE_OVERRIDE}
  />
);

export default Bathroom;
