"use client";

import { useEffect, useRef, useState } from "react";
import { CameraControls, CameraControlsImpl } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import {
  Box3,
  Mesh,
  MeshStandardMaterial,
  PlaneGeometry,
  Vector3,
  type Object3D,
} from "three";
import { ArrowDownToLine, ArrowUpToLine, BrickWall, RotateCcw } from "lucide-react";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import type { CameraConfig, SurfaceOverride } from "@/components/room-scene";
import { RoomScene } from "@/components/room-scene";
import type { Product } from "@/components/product-card";
import { cn } from "@/lib/utils";

/**
 * `modern_bathroom.glb` (sourced from Sketchfab, not generated by
 * `scripts/generate-room-models.mjs`). Its own camera rig and tileable-mesh
 * list live here rather than in `room-scene.tsx`'s internal maps — see
 * `components/visualizer/living-room.tsx` for the reasoning.
 */
const MODEL_URL = "/models/rooms/modern_bathroom.glb";

/**
 * The shell's interior, measured per mesh from the GLB itself: floor at
 * y 0.12, ceiling at y 2.45, left wall at x -1.44, right (window) wall at
 * x 1.46, back wall at z 1.89 (1.74 below the shelf). The model is a
 * three-walled set: nothing closes it at z -2.30, so any view with a side
 * wall in frame used to show the empty background past that edge.
 */
const SHELL = { minX: -1.44, maxX: 1.46, minY: 0.12, maxY: 2.45, frontZ: -2.3 };
const FRONT_WALL_NAME = "Bathroom_FrontWall";

/**
 * Floor and walls are separate meshes (no `combinedShell`), but
 * `Bathroom_SideWalls_0` still welds the ceiling into the wall geometry —
 * `peelCeilingFromWalls` tells `RoomScene` to keep those near-horizontal
 * faces on the plaster via `prepareWallGroups`. Both meshes also ship with
 * 0..1 UVs; metre UV rewrite happens in `RoomScene` the same way as the
 * living room. The front wall is ours (see `prepareBathroom`) and tiles with
 * the rest.
 */
const SURFACE_OVERRIDE: SurfaceOverride = {
  floor: ["Bathroom_Floor_0"],
  wall: ["Bathroom_BackWall_0", "Bathroom_SideWalls_0", FRONT_WALL_NAME],
  peelCeilingFromWalls: true,
};

/**
 * `Bathroom_SideWalls_0`'s own material is a baked atlas that is mostly grey
 * shading — as the ceiling (the only large surface still showing it once the
 * walls are tiled) it read as a dull, blotchy grey slab, and up close its
 * texels smeared into soft rows of blobs. A clean matte plaster reads as a
 * bathroom ceiling at any distance. The slight emissive lift offsets the
 * hemisphere light's warm-brown ground colour, which is what a downward-
 * facing surface mostly receives here.
 */
const PLASTER = new MeshStandardMaterial({
  name: "BathroomPlaster",
  color: 0xf4f2ee,
  emissive: 0xffffff,
  emissiveIntensity: 0.3,
  roughness: 0.95,
  metalness: 0,
});

/** Patches the model's own gaps; handed to `RoomScene` as `prepareScene`. */
const prepareBathroom = (room: Object3D) => {
  room.getObjectByName("Bathroom_SideWalls_0")?.traverse((object) => {
    if (object instanceof Mesh) object.material = PLASTER;
  });

  // Closes the open fourth side. A few millimetres wider and taller than the
  // opening so its edges tuck behind the side walls, floor and ceiling
  // instead of leaving a hairline seam.
  const width = SHELL.maxX - SHELL.minX + 0.02;
  const height = SHELL.maxY - SHELL.minY + 0.02;
  const frontWall = new Mesh(new PlaneGeometry(width, height), PLASTER);
  frontWall.name = FRONT_WALL_NAME;
  frontWall.position.set((SHELL.minX + SHELL.maxX) / 2, (SHELL.minY + SHELL.maxY) / 2, SHELL.frontZ);
  room.add(frontWall);

  // The glowing pane (`Bathroom_WindowLight_0`, at x 1.55) stops a few
  // centimetres short of the frame along its edge and arch, and there is
  // nothing outside the window, so at glancing angles those slivers showed
  // the empty background. A backing sheet of the same light, just inside
  // the reveal's outer edge (x 1.64), fills the whole opening
  // (z -0.13..1.14, up to the arch top at y 2.12).
  const pane = room.getObjectByName("Bathroom_WindowLight_0");
  if (pane instanceof Mesh) {
    const backing = new Mesh(new PlaneGeometry(1.4, 2.1), pane.material);
    backing.name = "Bathroom_WindowBacking";
    backing.rotation.y = -Math.PI / 2;
    backing.position.set(1.62, 1.13, 0.5);
    room.add(backing);
  }
};

const CAMERA_CONFIG: CameraConfig = {
  position: [0.1, 1.15, -1.95],
  target: [0.1, 1.05, 0.25],
  near: 0.01,
  far: 60,
  horizontalFov: 70,
  orbitLimits: {
    minDistance: 0.15,
    maxDistance: 2.5,
    // Keep free rotation in the useful floor-to-ceiling arc. Near-vertical
    // extremes put the camera just above a surface while looking through its
    // back face, which exposed the underside of the floor in particular.
    minPolarAngle: Math.PI / 12,
    maxPolarAngle: Math.PI * 3 / 4,
    minAzimuthAngle: Math.PI / 2,
    maxAzimuthAngle: Math.PI * 3 / 2,
  },
};

const VIEWS = {
  room: { position: CAMERA_CONFIG.position, target: CAMERA_CONFIG.target, label: "Reset view", icon: RotateCcw },
  floor: { position: [0.1, 2.1, -0.85], target: [0.1, 0.18, -0.25], label: "Floor view", icon: ArrowDownToLine },
  wall: { position: [-0.35, 1.35, -0.9], target: [-1.33, 1.35, -0.35], label: "Wall view", icon: BrickWall },
  ceiling: { position: [0.1, 1.1, -1.6], target: [0.1, 2.3, 0.1], label: "Ceiling view", icon: ArrowUpToLine },
} satisfies Record<string, { position: number[]; target: number[]; label: string; icon: typeof RotateCcw }>;

type View = keyof typeof VIEWS;
const ACTION = CameraControlsImpl.ACTION;
const MOUSE_BUTTONS = { left: ACTION.ROTATE, middle: ACTION.DOLLY, right: ACTION.NONE, wheel: ACTION.DOLLY };
const TOUCHES = { one: ACTION.TOUCH_ROTATE, two: ACTION.TOUCH_DOLLY_ROTATE, three: ACTION.NONE };

/**
 * Where the camera body may be. The near plane sits 1 cm out, so anything
 * the camera gets within a few centimetres of fills the frame as a blurred
 * slab — which is what the old box allowed: its x max *was* the window wall's
 * plane, and it reached into the corner boxing, the pendant and the cabinet.
 * This keeps a margin to every shell surface instead: a tight one to the
 * side and front walls, so a close look at the tile is possible, and a wider
 * one above the floor and below the ceiling, where the camera would otherwise
 * end up staring straight down or up at a blank plane. `max.z` stops in front
 * of the shelf and everything on it; the fixtures that stand further out
 * into the room are handled by `FIXTURE_ZONES`.
 */
const WALL_CLEARANCE = 0.12;
const CAMERA_ROOM = new Box3(
  new Vector3(SHELL.minX + WALL_CLEARANCE, SHELL.minY + 0.33, SHELL.frontZ + WALL_CLEARANCE),
  new Vector3(SHELL.maxX - WALL_CLEARANCE, SHELL.maxY - 0.3, 1.45),
);

/**
 * Fixtures that stand out into `CAMERA_ROOM`, as their measured bounds padded
 * by `FIXTURE_CLEARANCE`. The camera is pushed back out of these rather than
 * relying on camera-controls' collider raycasts, which only shorten the
 * target→camera line (the boundary clamp afterwards could still slide the
 * camera into a fixture) and cost four raycasts a frame against the ~40k-
 * triangle plant.
 */
const FIXTURE_CLEARANCE = 0.2;
const FIXTURE_ZONES = [
  // Sink cabinet
  [[-0.09, 0.12, 0.74], [0.86, 1.15, 1.82]],
  // Toilet
  [[-1.18, 0.1, 1.13], [-0.39, 1.02, 1.89]],
  // Potted plant
  [[0.92, 0.12, 0.99], [1.37, 1.36, 1.54]],
  // Pendant lamp and its cord
  [[-0.67, 1.62, 1.32], [-0.38, 2.45, 1.61]],
].map(([min, max]) =>
  new Box3(new Vector3(...min), new Vector3(...max)).expandByScalar(FIXTURE_CLEARANCE),
);

const exitCandidate = new Vector3();

/** Pushes `position` out through the nearest face of any zone it is inside that leads somewhere valid. */
const leaveFixtureZones = (position: Vector3) => {
  for (const zone of FIXTURE_ZONES) {
    if (!zone.containsPoint(position)) continue;
    const exits: [number, "x" | "y" | "z", number][] = [
      [position.x - zone.min.x, "x", zone.min.x],
      [zone.max.x - position.x, "x", zone.max.x],
      [position.y - zone.min.y, "y", zone.min.y],
      [zone.max.y - position.y, "y", zone.max.y],
      [position.z - zone.min.z, "z", zone.min.z],
      [zone.max.z - position.z, "z", zone.max.z],
    ];
    exits.sort((a, b) => a[0] - b[0]);
    const exit = exits.find(([, axis, value]) => {
      exitCandidate.copy(position).setComponent("xyz".indexOf(axis), value);
      return (
        CAMERA_ROOM.containsPoint(exitCandidate) &&
        FIXTURE_ZONES.every((other) => other === zone || !other.containsPoint(exitCandidate))
      );
    });
    if (!exit) return false;
    position.setComponent("xyz".indexOf(exit[1]), exit[2]);
  }
  return true;
};

/** Where the camera body actually ends up for a requested position; false if nowhere valid. */
const containPosition = (position: Vector3) => {
  position.clamp(CAMERA_ROOM.min, CAMERA_ROOM.max);
  return leaveFixtureZones(position);
};

/**
 * Along a ray from `origin`, the distance at which it last leaves `box`, or
 * null if it never passes through it. Orbit targets can sit outside
 * `CAMERA_ROOM` (the floor, wall and ceiling views aim just off a surface),
 * so this is the far slab crossing, not `Ray.intersectBox`'s nearest one.
 */
const exitDistance = (origin: Vector3, direction: Vector3, box: Box3) => {
  let near = 0;
  let far = Infinity;
  for (const axis of ["x", "y", "z"] as const) {
    const start = origin[axis];
    const step = direction[axis];
    if (Math.abs(step) < 1e-9) {
      if (start < box.min[axis] || start > box.max[axis]) return null;
      continue;
    }
    const a = (box.min[axis] - start) / step;
    const b = (box.max[axis] - start) / step;
    near = Math.max(near, Math.min(a, b));
    far = Math.min(far, Math.max(a, b));
  }
  return near <= far ? far : null;
};

/**
 * How far the lens can zoom once the camera itself can't get any closer.
 * 5× on the 70° lens frames roughly half a metre of wall from the far side
 * of the room — two or three tiles across, enough to read texture and grout.
 */
const MAX_LENS_ZOOM = 5;
/** Below this, a dolly step isn't a visible move — the containment is holding the camera. */
const MIN_VISIBLE_DOLLY = 0.005;

const orbitDirection = new Vector3();
const probeNow = new Vector3();
const probeNext = new Vector3();

/**
 * Wheel and pinch both go through `_dollyInternal`, so this is the one place
 * zoom behaviour lives. Dollying alone ran out quickly: every view orbits a
 * fixed target (the room view's sits mid-room, 1.6 m from the back wall),
 * so the camera stops at `minDistance` from that point, or at the wall
 * margin, long before a tile fills the frame. Past that point zooming in
 * narrows the lens instead, and zooming out opens the lens back to 1× before
 * the camera starts backing away.
 */
class BathroomCameraControlsImpl extends CameraControlsImpl {
  constructor(...args: ConstructorParameters<typeof CameraControlsImpl>) {
    super(...args);
    const dolly = this._dollyInternal;
    // Negative delta is "in", matching camera-controls' own convention.
    this._dollyInternal = (delta, x, y) => {
      if (delta > 0) {
        if (this._zoomEnd > 1.001) this.lensZoom(delta);
        else dolly(delta, x, y);
        return;
      }

      const { phi, theta } = this._sphericalEnd;
      orbitDirection.setFromSphericalCoords(1, phi, theta);
      // Backed out past the room, the first steps in would only shorten an
      // orbit the containment is already cutting short — no visible change.
      // Skip straight to where the orbit re-enters the room.
      const exit = exitDistance(this._targetEnd, orbitDirection, CAMERA_ROOM);
      if (exit !== null && this._sphericalEnd.radius > Math.max(exit, this.minDistance)) {
        void this.dollyTo(exit, true);
      }

      const radius = this._sphericalEnd.radius;
      const nextRadius = Math.min(
        Math.max(radius * Math.pow(0.95, -delta * this.dollySpeed), this.minDistance),
        this.maxDistance,
      );
      probeNow.copy(orbitDirection).multiplyScalar(radius).add(this._targetEnd);
      probeNext.copy(orbitDirection).multiplyScalar(nextRadius).add(this._targetEnd);
      const moves =
        containPosition(probeNow) &&
        containPosition(probeNext) &&
        probeNow.distanceTo(probeNext) > MIN_VISIBLE_DOLLY;
      if (moves) dolly(delta, x, y);
      else this.lensZoom(delta);
    };
  }

  private lensZoom(delta: number) {
    void this.zoomTo(this._zoomEnd * Math.pow(0.95, delta * this.dollySpeed), true);
  }
}

const lastValidPosition = new Vector3();

function BathroomControls({ view, revision }: { view: View; revision: number }) {
  const controls = useRef<CameraControlsImpl>(null);
  const camera = useThree((state) => state.camera);

  // Runs after drei's CameraControls (priority -1) has placed the camera for
  // this frame. The controls rebuild the position from their own spherical
  // state every frame, so this correction never accumulates or drifts: it
  // only moves the camera body, and the view keeps aiming the way the
  // controls pointed it.
  useFrame(() => {
    const position = camera.position;
    if (containPosition(position)) lastValidPosition.copy(position);
    else position.copy(lastValidPosition);

    // A drag that turns the view 10° at 1× would swing it 50° at 5×; scale
    // rotation with the lens so the picture moves at the same pace.
    const instance = controls.current;
    if (instance) {
      instance.azimuthRotateSpeed = 1 / camera.zoom;
      instance.polarRotateSpeed = 1 / camera.zoom;
    }
  });

  useEffect(() => {
    const instance = controls.current;
    if (!instance) return;
    const { position: p, target: t } = VIEWS[view];
    lastValidPosition.set(p[0], p[1], p[2]);
    // Reset the complete motion state too, including any queued wheel movement.
    void instance.setLookAt(p[0], p[1], p[2], t[0], t[1], t[2], false);
    void instance.zoomTo(1, false);
  }, [camera, view, revision]);

  return (
    <CameraControls
      ref={controls}
      impl={BathroomCameraControlsImpl}
      makeDefault
      smoothTime={0.22}
      draggingSmoothTime={0.1}
      dollySpeed={0.65}
      dollyToCursor={false}
      infinityDolly={false}
      minZoom={1}
      maxZoom={MAX_LENS_ZOOM}
      {...CAMERA_CONFIG.orbitLimits}
      mouseButtons={MOUSE_BUTTONS}
      touches={TOUCHES}
    />
  );
}

export const Bathroom = ({
  floorTile,
  wallTile,
  className,
}: {
  floorTile?: Product;
  wallTile?: Product;
  className?: string;
}) => {
  const [selection, setSelection] = useState<{ view: View; revision: number }>({ view: "room", revision: 0 });
  return (
    <div className={cn("relative", className)}>
      <RoomScene
        modelUrl={MODEL_URL}
        floorTile={floorTile}
        wallTile={wallTile}
        className="size-full"
        cameraConfig={CAMERA_CONFIG}
        surfaceOverride={SURFACE_OVERRIDE}
        prepareScene={prepareBathroom}
        controls={<BathroomControls {...selection} />}
      />
      <div
        className="absolute bottom-20 right-4 flex gap-1 rounded-lg bg-white/95 p-1 shadow-sm"
        role="toolbar"
        aria-label="Bathroom views"
      >
        {(Object.keys(VIEWS) as View[]).map((view) => {
          const { icon: Icon, label } = VIEWS[view];
          return (
            <Tooltip key={view}>
              <TooltipTrigger
                aria-label={label}
                className="flex size-10 items-center justify-center rounded-md text-foreground hover:bg-gray-100 focus-visible:outline-2 focus-visible:outline-primary"
                onClick={() => setSelection((current) => ({ view, revision: current.revision + 1 }))}
              >
                <Icon size={19} />
              </TooltipTrigger>
              <TooltipContent>{label}</TooltipContent>
            </Tooltip>
          );
        })}
      </div>
    </div>
  );
};

export default Bathroom;
