"use client";

import type { CameraConfig, SurfaceOverride } from "@/components/room-scene";
import { RoomScene } from "@/components/room-scene";
import type { Product } from "@/components/product-card";

/**
 * `modern_bathroom.glb` (sourced from Sketchfab, not generated by
 * `scripts/generate-room-models.mjs`). Its own camera rig and tileable-mesh
 * list live here rather than in `room-scene.tsx`'s internal maps — see
 * `components/visualizer/living-room.tsx` for the reasoning.
 */
const MODEL_URL = "/models/rooms/modern_bathroom.glb";

/**
 * Floor and walls are separate meshes (no `combinedShell`), but
 * `Bathroom_SideWalls_0` still welds the ceiling into the wall geometry —
 * `peelCeilingFromWalls` tells `RoomScene` to keep those near-horizontal
 * faces on the plaster via `prepareWallGroups`. Both meshes also ship with
 * 0..1 UVs; metre UV rewrite happens in `RoomScene` the same way as the
 * living room.
 */
const SURFACE_OVERRIDE: SurfaceOverride = {
  floor: ["Bathroom_Floor_0"],
  wall: ["Bathroom_BackWall_0", "Bathroom_SideWalls_0"],
  peelCeilingFromWalls: true,
};

/**
 * Measured the same way as the other sourced models: dumped
 * `Box3.setFromObject` per mesh from inside the browser. This one is a
 * narrow room — x -1.44..1.64 (3.08 m wide), z -2.30..1.90 (4.2 m deep),
 * floor at y≈0.12, ceiling at y≈2.45 — with every fixture (mirror, pendant
 * light, sink cabinet, toilet, framed art) mounted on the back wall at
 * z≈1.8-1.9, and the window on the right side wall (x≈1.55) roughly midway
 * down the room. The default camera sits a little lower and looks upward
 * enough to include the ceiling and upper front wall in the normal view,
 * while `zoomToCursor` lets wall close-ups follow the customer's pointer
 * instead of diving into the vanity.
 */
const CAMERA_CONFIG: CameraConfig = {
  position: [0.1, 0.84, -1.75],
  target: [0.1, 1.12, 0.45],
  near: 0.01,
  far: 60,
  horizontalFov: 70,
  zoomToCursor: true,
  orbitLimits: {
    // Close enough to read the tile's texture/grout lines up close; `bounds`
    // (not this number) is what actually stops at the room shell, so pulling
    // this in further can't newly expose the outside of the model.
    minDistance: 0.06,
    // Keep zoom-out within the room's usable camera volume. Pushing much past
    // this makes OrbitControls keep asking for a position outside the shell,
    // while `ContainCamera` clamps it back each frame at the corner, which
    // reads as flicker.
    maxDistance: 2.35,
    // Wide enough to inspect both side walls from inside the bathroom, but
    // short of the grazing angles that show past the front-left shell edge as
    // a cream slice of page background.
    minAzimuthAngle: (152 * Math.PI) / 180,
    maxAzimuthAngle: (208 * Math.PI) / 180,
    // Allow a clear ceiling/upper-wall view from the default angle, while
    // keeping the high overhead end below the actual ceiling plane.
    minPolarAngle: (62 * Math.PI) / 180,
    maxPolarAngle: (108 * Math.PI) / 180,
  },
  /**
   * Keeps the camera inside the room regardless of what the orbit limits
   * alone allow — the same guarantee as the other rooms' `bounds`, see
   * `ContainCamera` in `room-scene.tsx`. These are pulled just inside the
   * measured wall planes rather than the floor's outer rectangle. The floor
   * runs a little beyond the right window/wall plane (x≈1.55) and behind the
   * back wall plane (z≈1.74); letting the camera use those extra floor bounds
   * puts it through the wall, which is what exposes the outside background.
   */
  bounds: {
    min: [-1.34, 0.18, -2.2],
    max: [1.46, 2.3, 1.68],
  },
  targetBounds: {
    min: [-0.9, 0.45, -0.5],
    max: [1.05, 1.85, 1.45],
  },
};

export const Bathroom = ({
  floorTile,
  wallTile,
  className,
}: {
  floorTile?: Product;
  wallTile?: Product;
  className?: string;
}) => (
  <RoomScene
    modelUrl={MODEL_URL}
    floorTile={floorTile}
    wallTile={wallTile}
    className={className}
    cameraConfig={CAMERA_CONFIG}
    surfaceOverride={SURFACE_OVERRIDE}
  />
);

export default Bathroom;
