"use client";

import { Box3, BufferGeometry, Mesh, MeshStandardMaterial, PlaneGeometry, Vector3, type Object3D } from "three";
import type { SurfaceOverride } from "@/components/room-scene";
import type { Product } from "@/components/product-card";
import { fixtureZones, RoomWithCamera, type RoomCameraRig } from "@/components/visualizer/room-camera";
import { addSkirting } from "@/components/visualizer/room-trim";

/**
 * `modern_bedroom.glb` (sourced from Sketchfab, not generated by
 * `scripts/generate-room-models.mjs`). Its own camera rig and tileable-mesh
 * list live here rather than in `room-scene.tsx` — see
 * `components/visualizer/living-room.tsx` for the reasoning.
 */
const MODEL_URL = "/models/rooms/modern_bedroom.glb";

/**
 * The room, measured from the model's own shell triangles. It is centred on
 * the origin rather than sitting on it: floor at y -1.71, ceiling at y 1.71,
 * side walls at x ±2.57, and the window wall at z -3.09 — nearly all glass,
 * with a backdrop plane 1.8 m behind it at z -4.87 standing in for the view
 * out. Nothing closes the room at z 3.00; the old camera stood out there at
 * z 4.9 and looked in.
 */
const SHELL = { minX: -2.57, maxX: 2.57, minY: -1.71, maxY: 1.71, minZ: -3.09, maxZ: 3.0 };
const SHELL_MESH = "Bedroom_Bedroom_0";
const FRONT_WALL_NAME = "Bedroom_FrontWall";
const BACKDROP_NAME = "Bedroom_Backdrop";
const WINDOW_FEATURE_NAME = "Bedroom_WindowFeature";
/** Everything this far behind the window wall is the backdrop, not the room. */
const BACKDROP_MAX_Z = -4.5;
/** The nine decorative panels inside the centre window keep their baked design. */
const WINDOW_FEATURE = { minX: -0.9, maxX: 0.9, minY: -1.3, maxY: 1.3, minZ: -2.985, maxZ: -2.97 };

/**
 * `Bedroom_Bedroom_0` welds the room shell together with the bed, TV stand,
 * painting, nightstands and cupboards (51k triangles). `combinedShell`
 * splits floor/wall/ceiling by orientation, and `filterArchitecturalIslands`
 * in `room-scene.tsx` peels the furniture islands back onto the original
 * material so only the real shell takes the customer's tile.
 *
 * `Bedroom_Carpet_0` is its own mesh (the dark rug in front of the bed) and
 * deliberately stays untouched so selecting a floor tile does not hide it.
 * Duvet, windows/glasses and `Bedroom_Bedroom_0_1` also stay untouched. The
 * front wall is ours (see `prepareBedroom`) and tiles with the rest.
 */
const SURFACE_OVERRIDE: SurfaceOverride = {
  combinedShell: [SHELL_MESH],
  wall: [FRONT_WALL_NAME],
};

/** Clean plaster for the added fourth wall, matched to the bedroom's default grey. */
const PLASTER = new MeshStandardMaterial({
  name: "BedroomPlaster",
  color: 0xaaa9a3,
  roughness: 0.95,
  metalness: 0,
});

const worldVertex = new Vector3();

/** Patches the model's own gaps; handed to `RoomScene` as `prepareScene`. */
const prepareBedroom = (room: Object3D) => {
  room.updateMatrixWorld(true);

  // The backdrop behind the windows is the largest near-vertical surface in
  // the shell, so the orientation split took it for a wall and tiled it: the
  // windows looked out onto more tiles. Moved to its own mesh (a child, so
  // it keeps the shell's transform and baked material), the split never
  // sees it.
  room.traverse((object) => {
    if (!(object instanceof Mesh) || object.name !== SHELL_MESH) return;
    const geometry = object.geometry as BufferGeometry;
    const position = geometry.attributes.position;
    const index = geometry.index;
    const triangles = (index ? index.count : position.count) / 3;
    const vertexOf = (triangle: number, corner: number) =>
      index ? index.getX(triangle * 3 + corner) : triangle * 3 + corner;

    const keep: number[] = [];
    const backdrop: number[] = [];
    const windowFeature: number[] = [];
    for (let triangle = 0; triangle < triangles; triangle += 1) {
      const corners = [0, 1, 2].map((corner) => vertexOf(triangle, corner));
      const outside = corners.every(
        (vertex) =>
          worldVertex.fromBufferAttribute(position, vertex).applyMatrix4(object.matrixWorld).z < BACKDROP_MAX_Z,
      );
      const onWindowFeature = !outside && corners.every((vertex) => {
        worldVertex.fromBufferAttribute(position, vertex).applyMatrix4(object.matrixWorld);
        return (
          worldVertex.x >= WINDOW_FEATURE.minX &&
          worldVertex.x <= WINDOW_FEATURE.maxX &&
          worldVertex.y >= WINDOW_FEATURE.minY &&
          worldVertex.y <= WINDOW_FEATURE.maxY &&
          worldVertex.z >= WINDOW_FEATURE.minZ &&
          worldVertex.z <= WINDOW_FEATURE.maxZ
        );
      });
      (outside ? backdrop : onWindowFeature ? windowFeature : keep).push(...corners);
    }
    if (backdrop.length === 0) return;

    const makeUntiledPart = (name: string, indices: number[]) => {
      if (indices.length === 0) return;
      const partGeometry = geometry.clone();
      // `clone()` shares `userData`, where the split caches its results.
      partGeometry.userData = {};
      partGeometry.setIndex(indices);
      partGeometry.clearGroups();
      const part = new Mesh(partGeometry, object.material);
      part.name = name;
      object.add(part);
    };

    geometry.setIndex(keep);
    geometry.clearGroups();
    makeUntiledPart(BACKDROP_NAME, backdrop);
    makeUntiledPart(WINDOW_FEATURE_NAME, windowFeature);
  });

  // Closes the open side. A little oversized so its edges tuck behind the
  // side walls, floor and ceiling instead of leaving a seam.
  const width = SHELL.maxX - SHELL.minX + 0.02;
  const height = SHELL.maxY - SHELL.minY + 0.02;
  const frontWall = new Mesh(new PlaneGeometry(width, height), PLASTER);
  frontWall.name = FRONT_WALL_NAME;
  // A plane faces +z; turned to face -z, into the room.
  frontWall.rotation.y = Math.PI;
  frontWall.position.set((SHELL.minX + SHELL.maxX) / 2, (SHELL.minY + SHELL.maxY) / 2, SHELL.maxZ);
  room.add(frontWall);

  // Skirting round the floor. The side walls start at the window bay
  // (z -2.10); the window wall itself is glazed to within 9 cm of the floor
  // and hidden behind the bed, so it gets none.
  addSkirting(room, {
    floorY: SHELL.minY,
    walls: [
      { axis: "x", at: SHELL.minX, from: -2.1, to: SHELL.maxZ, inward: 1 },
      { axis: "x", at: SHELL.maxX, from: -2.1, to: SHELL.maxZ, inward: -1 },
      { axis: "z", at: SHELL.maxZ, from: SHELL.minX, to: SHELL.maxX, inward: -1 },
    ],
  });
};

const WALL_CLEARANCE = 0.12;

const RIG: RoomCameraRig = {
  config: {
    // Across the room at a diagonal, from the corner by the closed side:
    // the painting and TV unit on one wall, the bed and the glass wall
    // behind it, and the rug in between. The target sits on the wall above
    // the bed's far corner, so zooming all the way in ends on tile rather
    // than on the duvet.
    position: [2.2, 0.3, 2.6],
    target: [-1.3, -0.25, -2.6],
    near: 0.01,
    far: 60,
    horizontalFov: 70,
    orbitLimits: {
      minDistance: 0.15,
      // The room view's own target is 6.3 m away.
      maxDistance: 7,
      minAzimuthAngle: -Infinity,
      maxAzimuthAngle: Infinity,
      minPolarAngle: Math.PI / 12,
      maxPolarAngle: (Math.PI * 3) / 4,
    },
  },
  views: {
    // The open floor between the bed and the closed side, over the rug.
    floor: { position: [0.6, 1.0, 1.9], target: [0.6, SHELL.minY + 0.02, 0.9] },
    // The side wall opposite the TV unit — the room's clearest stretch of wall.
    wall: { position: [0.9, 0, -0.8], target: [SHELL.maxX - 0.12, 0, -0.8] },
    ceiling: { position: [-0.8, 0.2, 1.6], target: [0.2, SHELL.maxY - 0.06, -0.6] },
  },
  cameraRoom: new Box3(
    // The window wall is the one side the camera stays well back from: a
    // bulkhead over the window reaches a metre into the room at ceiling
    // height, and the bed and its nightstands do the same along the floor,
    // so a wall-clearance margin there put the lens inside them. Nothing is
    // tiled on that wall — it is glass — so there is nothing to come closer
    // for.
    new Vector3(SHELL.minX + WALL_CLEARANCE, SHELL.minY + 0.35, -1.9),
    new Vector3(SHELL.maxX - WALL_CLEARANCE, SHELL.maxY - 0.3, SHELL.maxZ - WALL_CLEARANCE),
  ),
  fixtureZones: fixtureZones(
    [
      // Bed, headboard and duvet. (The cupboards and nightstands against the
      // window wall sit beyond `cameraRoom`'s own limit there, so they need
      // no zone of their own.)
      [[-1.15, -1.71, -3.09], [0.95, -0.4, -0.35]],
      // The long TV unit along the left wall.
      [[-2.57, -1.71, -1.3], [-2.0, -0.45, 1.1]],
    ],
    0.2,
  ),
};

export const Bedroom = ({
  floorTile,
  wallTile,
  className,
}: {
  floorTile?: Product;
  wallTile?: Product;
  className?: string;
}) => (
  <RoomWithCamera
    modelUrl={MODEL_URL}
    floorTile={floorTile}
    wallTile={wallTile}
    className={className}
    rig={RIG}
    surfaceOverride={SURFACE_OVERRIDE}
    prepareScene={prepareBedroom}
  />
);

export default Bedroom;
