"use client";

import type { CameraConfig, SurfaceOverride } from "@/components/room-scene";
import { RoomScene } from "@/components/room-scene";
import type { Product } from "@/components/product-card";

/**
 * `modern_bedroom.glb` (sourced from Sketchfab, not generated by
 * `scripts/generate-room-models.mjs`). Its own camera rig and tileable-mesh
 * list live here rather than in `room-scene.tsx`'s internal maps — see
 * `components/visualizer/living-room.tsx` for the reasoning.
 */
const MODEL_URL = "/models/rooms/modern_bedroom.glb";

/**
 * `Bedroom_Bedroom_0` welds the room shell together with the bed, TV stand,
 * painting, nightstands and cupboards (51k triangles). `combinedShell`
 * splits floor/wall/ceiling by orientation, and `filterArchitecturalIslands`
 * in `room-scene.tsx` peels the furniture islands back onto the original
 * material so only the real shell takes the customer's tile.
 *
 * `Bedroom_Carpet_0` is its own mesh (the dark rug in front of the bed) —
 * list it as floor so it receives the same floor tile as the shell, instead
 * of staying on the model's flat Carpet material. Duvet, windows/glasses
 * and `Bedroom_Bedroom_0_1` stay untouched.
 */
const SURFACE_OVERRIDE: SurfaceOverride = {
  combinedShell: ["Bedroom_Bedroom_0"],
  floor: ["Bedroom_Carpet_0"],
};

/**
 * Matched to the Sketchfab listing's own preview: head-on to the window
 * wall, whole room in frame — both side walls, ceiling, bed cluster, and
 * the carpet in the foreground. `position`/`maxDistance` are the same
 * framing, so mounting and zooming all the way out land on that shot.
 *
 * Room shell (world): x ±2.66, y ±1.71, back wall z≈-3.09, open side past
 * z≈3. Camera stands in the open floor looking back at the bed.
 */
const CAMERA_CONFIG: CameraConfig = {
  position: [0, 0.25, 4.9],
  target: [0, -0.4, -1.6],
  near: 0.1,
  far: 60,
  horizontalFov: 58,
  orbitLimits: {
    minDistance: 4.0,
    // Mounting landed exactly on `maxDistance` before, which left no room
    // to actually zoom out any further than the default shot. Past that:
    // the Sketchfab reference framing.
    maxDistance: 7.80,
    minAzimuthAngle: (-12 * Math.PI) / 180,
    maxAzimuthAngle: (12 * Math.PI) / 180,
    minPolarAngle: (78 * Math.PI) / 180,
    maxPolarAngle: (90 * Math.PI) / 180,
  },
  /**
   * Keeps the camera inside the room regardless of what the orbit limits
   * alone allow — the same guarantee as the other rooms' `bounds`, see
   * `ContainCamera` in `room-scene.tsx`. `max.z` gives the wider
   * `maxDistance` above room to actually back up in; still stays short of
   * the open floor's own far edge and doesn't walk into the bed cluster.
   */
  bounds: {
    min: [-2.0, -1.4, 3.2],
    max: [2.0, 1.2, 7.0],
  },
};

export const Bedroom = ({
  floorTile,
  wallTile,
  className,
}: {
  floorTile?: Product;
  wallTile?: Product;
  className?: string;
}) => (
  <RoomScene
    modelUrl={MODEL_URL}
    floorTile={floorTile}
    wallTile={wallTile}
    className={className}
    cameraConfig={CAMERA_CONFIG}
    surfaceOverride={SURFACE_OVERRIDE}
  />
);

export default Bedroom;
