"use client";

import { Box3, Group, Mesh, MeshStandardMaterial, PlaneGeometry, Vector3, type Object3D } from "three";
import type { SurfaceOverride } from "@/components/room-scene";
import type { Product } from "@/components/product-card";
import { fixtureZones, RoomWithCamera, type RoomCameraRig } from "@/components/visualizer/room-camera";
import { addSkirting } from "@/components/visualizer/room-trim";

/**
 * `modern_kitchen.glb` (sourced from Sketchfab, not generated by
 * `scripts/generate-room-models.mjs`) — a whole open-plan ground floor:
 * kitchen run, island, and a stairwell beyond the tiled wall.
 */
const MODEL_URL = "/models/rooms/modern_kitchen.glb";

/**
 * The model is built about 2.25× life size: its ceiling is 5.5 m up, its
 * counters 2.07 m high and its stools 1.67 m tall. Left alone, the
 * customer's tile lands at its true physical size in a room that is more
 * than twice as big as a real one, so a 50 cm tile reads as a 22 cm one —
 * the only room in the visualizer where tile scale was wrong. Scaling the
 * model instead of the tiles fixes it for every surface at once, puts the
 * room (2.44 m ceiling, 0.92 m counters, 0.74 m stools) in the same range as
 * the other rooms, and lets everything below be written in real metres.
 */
const MODEL_SCALE = 1 / 2.25;
const SCALED_MODEL = "Kitchen_ScaledModel";

/**
 * The room at that scale, measured from the model's own shell triangles:
 * floor at y -0.08, ceiling at y 2.36, the window wall at z -1.98 (its
 * window is a bright panel behind an opening in the wall), the far wall at
 * z 3.31 and the tiled kitchen wall at x 3.07. Nothing closes the room at
 * x -2.88 — the old camera looked in from out there. Past x 2.22, z 1.91 a
 * partition hides the stairwell, which is why the camera keeps out of that
 * corner (see `fixtureZones`).
 */
const SHELL = { minX: -2.88, maxX: 3.07, minY: -0.08, maxY: 2.36, minZ: -1.98, maxZ: 3.31 };
const LEFT_WALL_NAME = "Kitchen_LeftWall";

/**
 * Both walls, despite the confusingly similar `*_Wall_0` names:
 *
 * - `WindowWall_Wall_0` is the wall the window sits in.
 * - `Structure_Wall_0` is the house shell, which the far wall is part of. It
 *   also carries the window's reveal welded into the same mesh;
 *   `prepareTileableGroups` separates that out so the tile lands on the wall
 *   and not on the few centimetres of jamb around the glass.
 * - `Tiles_Tiles_0` is the kitchen's own splashback wall behind the counters.
 *   It shipped with a baked brick texture and was left out of this list, so
 *   the one wall a customer most wants to see their tile on kept the model's
 *   bricks instead.
 *
 * `Kitchen_LeftWall` is ours (see `prepareKitchen`).
 */
const SURFACE_OVERRIDE: SurfaceOverride = {
  floor: ["Floor_Wall_0"],
  wall: ["WindowWall_Wall_0", "Structure_Wall_0", "Tiles_Tiles_0", LEFT_WALL_NAME],
};

/** Stands in for the missing wall until a tile is chosen; matches the model's own plaster. */
const PLASTER = new MeshStandardMaterial({
  name: "KitchenPlaster",
  color: 0xe8e7e3,
  roughness: 0.95,
  metalness: 0,
});

/** Patches the model's own gaps; handed to `RoomScene` as `prepareScene`. */
const prepareKitchen = (room: Object3D) => {
  // Everything the model ships with goes under one scaled group, so anything
  // added below is positioned in real metres rather than model units.
  if (!room.getObjectByName(SCALED_MODEL)) {
    const scaled = new Group();
    scaled.name = SCALED_MODEL;
    [...room.children].forEach((child) => scaled.add(child));
    scaled.scale.setScalar(MODEL_SCALE);
    room.add(scaled);
  }

  // Closes the open side. A little oversized so its edges tuck behind the
  // window and far walls, floor and ceiling instead of leaving a seam.
  const depth = SHELL.maxZ - SHELL.minZ + 0.02;
  const height = SHELL.maxY - SHELL.minY + 0.02;
  const leftWall = new Mesh(new PlaneGeometry(depth, height), PLASTER);
  leftWall.name = LEFT_WALL_NAME;
  // A plane faces +z; turned to face +x, into the room.
  leftWall.rotation.y = Math.PI / 2;
  leftWall.position.set(SHELL.minX, (SHELL.minY + SHELL.maxY) / 2, (SHELL.minZ + SHELL.maxZ) / 2);
  room.add(leftWall);

  // Skirting round the floor, in real metres like the wall above (the model
  // itself is inside the scaled group). The stair partition at the back
  // right gets its own run; the window sits 21 cm above the floor, so the
  // window wall needs no gap.
  addSkirting(room, {
    floorY: SHELL.minY,
    walls: [
      { axis: "x", at: SHELL.minX, from: SHELL.minZ, to: SHELL.maxZ, inward: 1 },
      { axis: "x", at: SHELL.maxX, from: SHELL.minZ, to: 1.91, inward: -1 },
      { axis: "z", at: SHELL.minZ, from: SHELL.minX, to: SHELL.maxX, inward: 1 },
      { axis: "z", at: SHELL.maxZ, from: SHELL.minX, to: SHELL.maxX, inward: -1 },
      { axis: "z", at: 1.91, from: 2.22, to: SHELL.maxX, inward: -1 },
    ],
  });

  room.updateMatrixWorld(true);
};

const WALL_CLEARANCE = 0.12;

const RIG: RoomCameraRig = {
  config: {
    // From the open floor at the far side, across the island to the counter
    // run. The target is on the splashback wall between the counter and the
    // wall units, so zooming all the way in ends on tile.
    position: [-2.0, 1.5, 2.6],
    // Aimed at the splashback above the hob rather than at the counter
    // itself, so the deepest zoom frames tile instead of the cooktop.
    target: [2.95, 1.22, 0.9],
    near: 0.01,
    far: 60,
    horizontalFov: 70,
    orbitLimits: {
      minDistance: 0.15,
      // The room view's own target is 5.3 m away.
      maxDistance: 6,
      minAzimuthAngle: -Infinity,
      maxAzimuthAngle: Infinity,
      minPolarAngle: Math.PI / 12,
      maxPolarAngle: (Math.PI * 3) / 4,
    },
  },
  views: {
    // The open floor in front of the island.
    floor: { position: [0.7, 1.9, 1.4], target: [0.7, -0.05, 2.6] },
    // The splashback behind the counters — the kitchen's tiled wall.
    wall: { position: [1.4, 1.15, 0.3], target: [2.95, 1.05, 0.3] },
    // Up past the island's pendant lights.
    ceiling: { position: [-1.6, 1.2, 2.3], target: [0.1, 2.3, 0.8] },
  },
  cameraRoom: new Box3(
    new Vector3(SHELL.minX + WALL_CLEARANCE, SHELL.minY + 0.33, SHELL.minZ + WALL_CLEARANCE),
    new Vector3(SHELL.maxX - WALL_CLEARANCE, SHELL.maxY - 0.3, SHELL.maxZ - WALL_CLEARANCE),
  ),
  fixtureZones: fixtureZones(
    [
      // Island, its stools and the pendant lights hanging over it.
      [[-1.0, -0.08, -0.89], [0.24, 2.36, 1.89]],
      // Counter run: base units, splashback, wall units and the oven column.
      [[1.85, -0.08, -1.98], [3.07, 2.36, 1.93]],
      // Behind the partition at the back corner is the stairwell, not the kitchen.
      [[2.22, -0.08, 1.89], [3.07, 2.36, 3.31]],
    ],
    0.2,
  ),
};

export const Kitchen = ({
  floorTile,
  wallTile,
  className,
}: {
  floorTile?: Product;
  wallTile?: Product;
  className?: string;
}) => (
  <RoomWithCamera
    modelUrl={MODEL_URL}
    floorTile={floorTile}
    wallTile={wallTile}
    className={className}
    rig={RIG}
    surfaceOverride={SURFACE_OVERRIDE}
    prepareScene={prepareKitchen}
  />
);

export default Kitchen;
