"use client";

import { Box3, BufferGeometry, Mesh, MeshStandardMaterial, PlaneGeometry, Vector3, type Object3D } from "three";
import type { SurfaceOverride } from "@/components/room-scene";
import type { Product } from "@/components/product-card";
import { fixtureZones, RoomWithCamera, type RoomCameraRig } from "@/components/visualizer/room-camera";
import { addSkirting } from "@/components/visualizer/room-trim";

/**
 * `white_modern_living_room.glb` (sourced from Sketchfab, not generated by
 * `scripts/generate-room-models.mjs`). Its own camera rig and tileable-mesh
 * list live here rather than in `room-scene.tsx`'s internal maps — the point
 * of `RoomScene` taking both as props is that each sourced model's tuning
 * stays in its own small file instead of piling into one shared one.
 */
const MODEL_URL = "/models/rooms/white_modern_living_room.glb";

/**
 * The room, measured from the GLB's own shell triangles: floor at y -0.21,
 * ceiling at y 2.85, the art wall at x -2.68, the TV wall at z -2.46 and the
 * glass-door wall at z 2.46 (a 4.3 m opening, x ±2.15, glazed at z 2.54 and
 * 2.61). Nothing closes the room at x 2.68 — the old camera stood out there
 * and looked in through the gap — and behind the glass, at z 3.26, a large
 * sky backdrop fills the view out.
 */
const SHELL = { minX: -2.68, maxX: 2.68, minY: -0.21, maxY: 2.85, minZ: -2.46, maxZ: 2.46 };
const SHELL_MESH = "Structure_Structure_0";
const RIGHT_WALL_NAME = "LivingRoom_RightWall";
const BACKDROP_NAME = "LivingRoom_Backdrop";
const BACKDROP_MIN_Z = 3;

/**
 * The model welds floor, walls, ceiling — and the backdrop — into one mesh,
 * so `combinedShell` splits it by face orientation (`splitByOrientation` in
 * `room-scene.tsx`). The added right wall is tileable too; its plaster only
 * appears as the fallback while a selected wall texture is loading.
 */
const SURFACE_OVERRIDE: SurfaceOverride = {
  combinedShell: [SHELL_MESH],
  wall: [RIGHT_WALL_NAME],
};

/**
 * Fallback for the missing wall while a selected tile texture loads or cannot
 * be fetched. Sampling the source shell's untouched side wall gives #b1b4b5;
 * its material also uses the same texture as a full-strength emissive map, so
 * mirror that lift here to keep the fallback visually consistent.
 */
const PLASTER = new MeshStandardMaterial({
  name: "LivingRoomPlaster",
  color: 0xb1b4b5,
  emissive: 0xb1b4b5,
  emissiveIntensity: 1,
  roughness: 0.82,
  metalness: 0,
});

const worldVertex = new Vector3();

/** Patches the model's own gaps; handed to `RoomScene` as `prepareScene`. */
const prepareLivingRoom = (room: Object3D) => {
  room.updateWorldMatrix(true, true);

  // The sky backdrop is the largest near-vertical surface in the shell, so
  // the orientation split kept it as wall and tiled it: the glass doors
  // looked out onto more tiles. Moved to its own mesh (a child, so it keeps
  // the shell's transform and baked material), the split never sees it.
  const shell = room.getObjectByName(SHELL_MESH);
  if (shell instanceof Mesh) {
    const geometry = shell.geometry as BufferGeometry;
    const index = geometry.index;
    const position = geometry.attributes.position;
    if (index) {
      const keep: number[] = [];
      const backdrop: number[] = [];
      for (let triangle = 0; triangle < index.count / 3; triangle += 1) {
        const corners = [0, 1, 2].map((corner) => index.getX(triangle * 3 + corner));
        const outside = corners.every(
          (vertex) =>
            worldVertex.fromBufferAttribute(position, vertex).applyMatrix4(shell.matrixWorld).z > BACKDROP_MIN_Z,
        );
        (outside ? backdrop : keep).push(...corners);
      }
      if (backdrop.length > 0) {
        const backdropGeometry = geometry.clone();
        // `clone()` shares `userData`, where the split caches its results.
        backdropGeometry.userData = {};
        backdropGeometry.setIndex(backdrop);
        backdropGeometry.clearGroups();
        geometry.setIndex(keep);
        geometry.clearGroups();
        const backdropMesh = new Mesh(backdropGeometry, shell.material);
        backdropMesh.name = BACKDROP_NAME;
        shell.add(backdropMesh);
      }
    }
  }

  // Closes the open side. A little oversized so its edges tuck behind the
  // front and back walls, floor and ceiling instead of leaving a seam.
  const depth = SHELL.maxZ - SHELL.minZ + 0.02;
  const height = SHELL.maxY - SHELL.minY + 0.02;
  const rightWall = new Mesh(new PlaneGeometry(depth, height), PLASTER);
  rightWall.name = RIGHT_WALL_NAME;
  // A plane faces +z; turned to face -x, into the room.
  rightWall.rotation.y = -Math.PI / 2;
  rightWall.position.set(SHELL.maxX, (SHELL.minY + SHELL.maxY) / 2, (SHELL.minZ + SHELL.maxZ) / 2);
  room.add(rightWall);

  // Skirting round the floor. The glass-door wall's run is split either side
  // of the 4.3 m opening (x ±2.15).
  addSkirting(room, {
    floorY: SHELL.minY,
    walls: [
      { axis: "x", at: SHELL.minX, from: SHELL.minZ, to: SHELL.maxZ, inward: 1 },
      { axis: "x", at: SHELL.maxX, from: SHELL.minZ, to: SHELL.maxZ, inward: -1 },
      { axis: "z", at: SHELL.minZ, from: SHELL.minX, to: SHELL.maxX, inward: 1 },
      { axis: "z", at: SHELL.maxZ, from: SHELL.minX, to: -2.15, inward: -1 },
      { axis: "z", at: SHELL.maxZ, from: 2.15, to: SHELL.maxX, inward: -1 },
    ],
  });
};

const WALL_CLEARANCE = 0.12;

const RIG: RoomCameraRig = {
  config: {
    // From the new right wall's end of the room, by the glass doors, across
    // the sofa to the art wall, the lamp and the TV. The target is on the TV
    // wall, in the clear stretch between the lamp and the TV, so zooming all
    // the way in ends on tile rather than on the back of the sofa.
    position: [2.3, 1.55, 1.9],
    target: [-1.0, 1.2, -2.34],
    near: 0.01,
    far: 60,
    horizontalFov: 70,
    orbitLimits: {
      minDistance: 0.15,
      // The room view's own target is 5.3 m away.
      maxDistance: 5.5,
      // The room is closed on every side now, so the view can turn all the
      // way round, glass doors included.
      minAzimuthAngle: -Infinity,
      maxAzimuthAngle: Infinity,
      minPolarAngle: Math.PI / 12,
      maxPolarAngle: (Math.PI * 3) / 4,
    },
  },
  views: {
    // The open floor between the TV and the sofa.
    floor: { position: [1.9, 2.3, 0.7], target: [1.3, -0.15, -0.6] },
    // The right wall: the only wall with nothing hung on it.
    wall: { position: [0.9, 1.35, 0.6], target: [SHELL.maxX - 0.12, 1.3, 0] },
    ceiling: { position: [1.9, 1.2, 1.4], target: [0.6, 2.72, 0] },
  },
  cameraRoom: new Box3(
    new Vector3(SHELL.minX + WALL_CLEARANCE, SHELL.minY + 0.33, SHELL.minZ + WALL_CLEARANCE),
    new Vector3(SHELL.maxX - WALL_CLEARANCE, SHELL.maxY - 0.3, SHELL.maxZ - WALL_CLEARANCE),
  ),
  fixtureZones: fixtureZones(
    [
      // L-shaped sofa and its cushions (the coffee table sits inside it).
      [[-2.39, -0.21, -1.6], [1.48, 0.64, 2.28]],
      // Floor lamp, including its head.
      [[-2.28, -0.21, -2.28], [-1.39, 1.72, -1.68]],
      // TV stand.
      [[-0.62, -0.21, -2.46], [1.53, 0.61, -2.21]],
      // Wall shelf, its plant and the picture frame above it.
      [[-2.69, 1.33, 0.83], [-2.46, 1.99, 1.83]],
    ],
    0.2,
  ),
};

export const LivingRoom = ({
  floorTile,
  wallTile,
  className,
}: {
  floorTile?: Product;
  wallTile?: Product;
  className?: string;
}) => (
  <RoomWithCamera
    modelUrl={MODEL_URL}
    floorTile={floorTile}
    wallTile={wallTile}
    className={className}
    rig={RIG}
    surfaceOverride={SURFACE_OVERRIDE}
    prepareScene={prepareLivingRoom}
  />
);

export default LivingRoom;
