"use client";

import type { CameraConfig, SurfaceOverride } from "@/components/room-scene";
import { RoomScene } from "@/components/room-scene";
import type { Product } from "@/components/product-card";

/**
 * `white_modern_living_room.glb` (sourced from Sketchfab, not generated by
 * `scripts/generate-room-models.mjs`). Its own camera rig and tileable-mesh
 * list live here rather than in `room-scene.tsx`'s internal maps — the point
 * of `RoomScene` taking both as props is that each sourced model's tuning
 * stays in its own small file instead of piling into one shared one (see
 * `modern_kitchen.glb`'s entries there, kept as the pattern for callers that
 * predate this component).
 */
const MODEL_URL = "/models/rooms/white_modern_living_room.glb";

/**
 * Unlike the kitchen, this model has no separate floor mesh at all: the
 * whole shell — floor, walls, ceiling — is one welded surface,
 * `Structure_Structure_0`. `combinedShell` tells `RoomScene` to split it by
 * face orientation (see `splitByOrientation` in `room-scene.tsx`) rather
 * than by name.
 */
const SURFACE_OVERRIDE: SurfaceOverride = {
  combinedShell: ["Structure_Structure_0"],
};

/**
 * Measured the same way as the kitchen's rig: dumped `Box3.setFromObject`
 * per mesh from inside the browser rather than guessed — and, since this
 * model welds floor/wall/ceiling into one mesh, also by temporarily hiding
 * the ceiling group (see `splitByOrientation`) and looking straight down to
 * read the floor plan directly rather than inferring it from furniture.
 * That's what showed the sofa/TV/lamp/art cluster (x -2.7..1.5, z -2.5..2.6)
 * isn't a walled-off room at all: it's an open-plan nook, walled only on two
 * sides (the art wall at x≈-2.67 and the TV wall at z≈-2.46), with the
 * marble floor continuing past it, unobstructed, in +x. Every camera spot
 * inside the furniture cluster itself was too close to something — the sofa
 * alone nearly fills it — so the camera stands out in that open floor
 * instead, the way someone would in an open-plan space, looking back across
 * the whole sofa curve at the TV and art wall together.
 *
 * That open floor isn't uniformly clear, though: past roughly x=5, z=1.5-2
 * there's a doorway-style wall return (found the same way — aiming the
 * camera at candidate points and looking for a flat surface filling the
 * frame from close range) leading into an adjoining space this component
 * has no business rendering. `bounds`/`orbitLimits` below were verified by
 * driving the camera to every combination of their own edges (each corner
 * of the azimuth/polar/distance ranges, plus the resulting clamped
 * positions) and confirming none of them land in or past that return.
 */
const CAMERA_CONFIG: CameraConfig = {
  position: [4.0, 1.5, 1.0],
  target: [-1.0, 0.7, -0.8],
  near: 0.1,
  far: 100,
  horizontalFov: 60,
  orbitLimits: {
    // Pull in for a close look at tiles; bounds still keep clear of furniture.
    minDistance: 1.5,
    maxDistance: 7.5,
    minAzimuthAngle: (30 * Math.PI) / 180,
    maxAzimuthAngle: (100 * Math.PI) / 180,
    minPolarAngle: (60 * Math.PI) / 180,
    maxPolarAngle: (98 * Math.PI) / 180,
  },
  /**
   * Keeps the camera inside the room regardless of what the orbit limits
   * alone allow, the same guarantee as the kitchen's `bounds` — see
   * `ContainCamera` in `room-scene.tsx`. `max.x`/`max.z` stop short of the
   * doorway return described above (measured near x≈5, z≈1.7-2). `min.x`
   * is loose enough that minDistance can actually reach a close tile view
   * rather than being clamped in the open floor far from the sofa.
   */
  bounds: {
    min: [0.6, 0.3, -0.8],
    max: [5.2, 2.3, 3.2],
  },
};

export const LivingRoom = ({
  floorTile,
  wallTile,
  className,
}: {
  floorTile?: Product;
  wallTile?: Product;
  className?: string;
}) => (
  <RoomScene
    modelUrl={MODEL_URL}
    floorTile={floorTile}
    wallTile={wallTile}
    className={className}
    cameraConfig={CAMERA_CONFIG}
    surfaceOverride={SURFACE_OVERRIDE}
  />
);

export default LivingRoom;
